name: dashboard
channels:
  - conda-forge
dependencies:
  - python=3.9
  - sqlalchemy
  - pip
  - pip:
      - ccxt
      - streamlit
      - watchdog
      - plotly
      - numpy
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pandas_ta
      - pyyaml
      - commlib-py
      - git+https://github.com/hummingbot/hbot-remote-client-py.git
      - git+https://github.com/devamin/docker-manager.git@feat/docker-python-sdk

